services:
  - type: web
    name: recio-solutions
    runtime: static
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /404
        destination: /404.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
